### PR TITLE
Convert to onnx

### PR DESCRIPTION
**Pull request by ajinkya933**

### CODE REVIEW

**Comment by lamhoangtung** [comment]
Hi @ajinkya933. I'm trying to follow your instruction. You said:
 "Navigate to `pytorch/torch/onnx/symbolic_opset9.py` ". But when I navigate to `/usr/local/lib/python3.6/site-packages/torch/onnx`. I only see this:

```
.
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-36.pyc
│   ├── operators.cpython-36.pyc
│   ├── symbolic.cpython-36.pyc
│   └── utils.cpython-36.pyc
├── operators.py
├── symbolic.py
└── utils.py
```
So ... Where is the `symbolic_opset9.py` file ??

Also after modify your code a bit for CPU to this:
```python
import torch
from torch.autograd import Variable
import cv2
import imgproc
from craft import CRAFT
from collections import OrderedDict


def copyStateDict(state_dict):
    if list(state_dict.keys())[0].startswith("module"):
        start_idx = 1
    else:
        start_idx = 0
    new_state_dict = OrderedDict()
    for k, v in state_dict.items():
        name = ".".join(k.split(".")[start_idx:])
        new_state_dict[name] = v
    return new_state_dict

# load net
net = CRAFT()     # initialize
#net = net.cuda()
#net = torch.nn.DataParallel(net)

net.load_state_dict(copyStateDict(torch.load('./weights/craft_mlt_25k.pth', map_location='cpu')))
net.eval()

# load data
image = imgproc.loadImage('./template/back.png')

# resize
img_resized, target_ratio, size_heatmap = imgproc.resize_aspect_ratio(image, 1280, interpolation=cv2.INTER_LINEAR, mag_ratio=1.5)
ratio_h = ratio_w = 1 / target_ratio

# preprocessing
x = imgproc.normalizeMeanVariance(img_resized)
x = torch.from_numpy(x).permute(2, 0, 1)    # [h, w, c] to [c, h, w]
x = Variable(x.unsqueeze(0))                # [c, h, w] to [b, c, h, w]
#x = x.cuda()

from collections import OrderedDict

# trace export
torch.onnx.export(net,
  		  x,
                  'craft.onnx',
                  export_params=True,
                  verbose=True)
```
I ran it any ways and got this error:
```bash
Traceback (most recent call last):
  File "onnx.py", line 48, in <module>
    verbose=True)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/usr/local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible
```

Any ideal how to resolve all of this? Thanks a lot :P @ajinkya933

**Comment by lamhoangtung** [comment]
Ah okay it worked with PyTorch 1.3.0

**Comment by ajinkya933** [comment]
@lamhoangtung If you know  pls tell me how to convert LinkRefiner (https://drive.google.com/file/d/1XSaFwBkOaFOdtk4Ane3DFyJGPRw6v5bO/view) to onxx and run it along with craft.onnx to give line level detection ?

**Comment by lamhoangtung** [comment]
> @lamhoangtung If you know pls tell me how to convert LinkRefiner (https://drive.google.com/file/d/1XSaFwBkOaFOdtk4Ane3DFyJGPRw6v5bO/view) to onxx and run it along with craft.onnx to give line level detection ?

Okay will give it a try mate :P

**Comment by SaeedArisha** [comment]
Can anyone help me in performing detection using onnx model?

**Pull request closed without merging**
